// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTiKYKBuaIbswiX1uuPHGArP4FjS_6olo',
    appId: '1:670064840339:web:02481ffc81c9ff4ad8c766',
    messagingSenderId: '670064840339',
    projectId: 'jih-ijtema',
    authDomain: 'jih-ijtema.firebaseapp.com',
    storageBucket: 'jih-ijtema.appspot.com',
    measurementId: 'G-0FK4JFBJ25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0667FspleBfrOmxkfXjf5x09d9a27FEU',
    appId: '1:670064840339:android:280d8417876aba5bd8c766',
    messagingSenderId: '670064840339',
    projectId: 'jih-ijtema',
    storageBucket: 'jih-ijtema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ1W1EHLigUJ-a0gx2jL8aOPB5Ib65Lc8',
    appId: '1:670064840339:ios:5ed11afc4557bb81d8c766',
    messagingSenderId: '670064840339',
    projectId: 'jih-ijtema',
    storageBucket: 'jih-ijtema.appspot.com',
    iosBundleId: 'com.example.stFlutterStarterTemplate',
  );
}
