<?php
return [
        'Create Registrations',
        'Edit Registrations',
        'Delete Registrations',
        'View Registrations',
        "Create Members",
        "Edit Members",
        "Delete Members",
        "View Members",
        "View TravelReport",
        "View HealthReport",
        "View TourReport",
        "View FinancialsReport",
        "Create Notifications",
        "Edit Notifications",
        "Delete Notifications",
        "View Notifications",
        "Create Permissions",
        "Edit Permissions",
        "Delete Permissions",
        "View Permissions",
        "Create Users",
        "Edit Users",
        "Delete Users",
        "View Users",
];